services:
  broker:
    image: ghcr.io/d8-x/d8x-broker-server:main
    restart: always
    ports:
      # Default svc port is 8000
      - 127.0.0.1:8000:8000
    environment:
      BROKER_KEY: "${BROKER_KEY}"
      BROKER_FEE_TBPS: "${BROKER_FEE_TBPS}"
      CONFIG_PATH: /chain_config
    configs:
      - chain_config
configs:
  chain_config:
    file: ./chainConfig.json
